name: ECWE Backend CI/CD

on:
  
  workflow_dispatch:
    inputs:
      build_and_deploy:
        description: Builds and Deploys application
        required: true
        type: boolean
        default: true

      build_image_tag:
        description: Build Image Tag (Optional)
        required: false
        type: string
        default: v0.0.0

      deploy_only:
        description: Deploys application
        required: true
        type: boolean
        default: true

      environment:
        description: Backend Web App environment
        required: true
        type: choice
        options:
          - dev
          - uat
        default: dev

jobs:
  build_and_push_image:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set image name
        run: |
          set -x
          if [ "${{ github.event_name }}" == "push" ]; then
            BRANCH_NAME=${GITHUB_REF##*/}
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME=${{ github.base_ref }}
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            BRANCH_NAME=${GITHUB_REF##*/}
          fi
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.build_image_tag }}" != "v0.0.0" ]; then
            IMAGE_TAG=${{ github.event.inputs.build_image_tag }}
          else
            IMAGE_TAG=$BRANCH_NAME-${GITHUB_SHA::7}
          fi 
          echo "$IMAGE_TAG"
          echo "IMAGE_NAME=${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.APP_NAME }}:$IMAGE_TAG" >> $GITHUB_ENV
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR task
        run: |
          az acr task create --registry chaos1990 --name myTask --file acr_task.yml --context /dev/null --assign-identity /subscriptions/a86b02d4-bdfe-4fec-b63a-18c61d992583/resourceGroups/acr-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/acrId
      - name: acr cred
        run: az acr task credential add --name myTask --registry chaos1990 --login-server chaos1990.azurecr.io --use-identity ${{ secrets.AZURE_CLIENT_ID }}
      - name: acr task run    
        run: az acr task run --registry chaos1990 --name myTask
